### ISSUE TITLE
what the purpose of having `assert input_size % 32 == 0` in the code?

### ISSUE THREAD

**Issue by isalirezag** [tonylins/pytorch-mobilenet-v2#15]
I dont get the meaning of `        assert input_size % 32 == 0` in the code.
why do we want the input size be divisible by 32?

**Comment by odysseaspap** [comment]
Any updated on this? I have the same question.

**Comment by LucienXian** [comment]
@odysseaspap @isalirezag @tonylins I have the same question. Can you explain about it?

**Comment by jiamingNo1** [comment]
224/7=32
