### ISSUE TITLE
Extra 1k parameters compared to TF

### ISSUE THREAD

**Issue by nekulkarni** [tonylins/pytorch-mobilenet-v2#19]
The README mentions that number of parameters in this model is higher than those from official TF version by 1k (3.471 M vs 3.47 M). Why is that so?

**Comment by nekulkarni** [comment]
@tonylins waiting for your response. Thanks so much!

**Comment by tonylins** [comment]
@nekulkarni The official TF version rounds the number of parameters to decimal places. While I keep 3 decimal places.
