### ISSUE TITLE
about the Flops and params

### ISSUE THREAD

**Issue by windid** [tonylins/pytorch-mobilenet-v2#2]
I've measured this implementation using this script:
https://github.com/ShichenLiu/CondenseNet/blob/master/utils.py

and got the following result:
FLOPs: 320.19M, Params: 3.51M

which is slightly higher than the paper.
I just confusing about this.

**Comment by tonylins** [comment]
Thanks so much! I just find out the problem. The official TF implementation has a small difference against paper. I have modified my implementation accordingly and upload the new pretrained model. The statistics look identical now.
