### ISSUE TITLE
type error when loading model

### ISSUE THREAD

**Issue by liuyanqi** [tonylins/pytorch-mobilenet-v2#25]
Hi,

I clone the repo and made my own file main.py which has two lines:
from MobileNetV2 import MobileNetV2

net = MobileNetV2(n_class=1000)

However, when I run main, it gives me the following error:

  File "main.py", line 3, in <module>
    net = MobileNetV2(n_class=1000)
  File "/home/liuyanqi/pytorch-mobilenet-v2/MobileNetV2.py", line 89, in __init__
    self.features.append(block(input_channel, output_channel, s, expand_ratio=t))
  File "/home/liuyanqi/pytorch-mobilenet-v2/MobileNetV2.py", line 33, in __init__
    nn.Conv2d(hidden_dim, hidden_dim, 3, stride, 1, groups=hidden_dim, bias=False),
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 297, in __init__
    False, _pair(0), groups, bias)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 33, in __init__
    out_channels, in_channels // groups, *kernel_size))
TypeError: new() received an invalid combination of arguments - got (float, float, int, int), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
 * (object data, torch.device device)

I'm using pytorch 0.4.0 and python 2.7. Any help would be appreciated.

Thanks in advance!

**Comment by liuyanqi** [comment]
Resolved!

**Comment by liuyanqi** [comment]
resolved

**Comment by YellowKyu** [comment]
Hello @liuyanqi , how did you manage to fix this issue ? I'm getting the same error ...

Edit: I found a solution, not sure if it is the way to go though, I replaced : 
`hidden_dim = round(inp * expand_ratio)`
by
`hidden_dim = int(round(inp * expand_ratio))`
