### ISSUE TITLE
temporal shift module error

### ISSUE THREAD

**Issue by ys-dpc** [tonylins/pytorch-mobilenet-v2#29]
Hello

First of all thank you for your selfless open source, very good work!!!

Actually I want to question in the TSM program, but can't find the entrance to the questions, so I can only come here to ask questions, because the TSM within the project does not provide ucf101 and hmdb51 datasets split. txt file, The TSN project have related code but a lot of extra libraries to install, so I had to write my own code to generate the split. TXT file and run it with the command-line arguments you provided, but in the end the result is very poor（only 1.3%）, I think it is because there is an error in the split. txt file I generated, so I want to see the internal data form of the split. txt file you generated, is that ok?
My split. txt data format is：
/home/dpc/3D-ResNets-PyTorch-master/data/test_jpg/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01.avi 121 0
/home/dpc/3D-ResNets-PyTorch-master/data/test_jpg/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c02.avi 118 0
/home/dpc/3D-ResNets-PyTorch-master/data/test_jpg/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c03.avi 147 0
......

My RGB frame directory format is：
ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01.avi/img_00001.jpg
ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01.avi/img_00002.jpg
ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01.avi/img_00003.jpg
......

In fact, I'm still not sure what caused the low accuracy......

I would be very grateful if I could receive your reply！ ：）

**Comment by tonylins** [comment]
Hi, sorry that I did not see the issue. Has the problem been resolved? If not, feel free to post one in the TSM repo.
