### ISSUE TITLE
the pretrained model file is broken, could you provide a right ?

### ISSUE THREAD

**Issue by dancingpipi** [tonylins/pytorch-mobilenet-v2#30]
I have download the file , and uncompress it:
```
tar xvf mobilenet_v2.pth.tar
```
it turn out :
```
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```
it seem some error occur with the model file, could you provide a new one?

**Comment by JisongXie** [comment]
You don't need to unzip it. See the example, it just load it.
`state_dict = torch.load('mobilenetv2.pth.tar')`
