### ISSUE TITLE
problem about the last version of MobileNetV2

### ISSUE THREAD

**Issue by zhouyuan888888** [tonylins/pytorch-mobilenet-v2#32]
Hi，Can you provided the pretrained model of MobileNetV2 in your last version. thankyou~

**Comment by salmedina** [comment]
I downloaded from GDrive but cannot untar it. Is the pretrained tar file broken?
I tried extracting it through:
`tar -xvf mobilenet_v2.pth.tar`

**Comment by tonylins** [comment]
Hi @salmedina , you are not supposed to untar the file. Just load it into PyTorch using something like torch.load(filename). I find that more than one person is confused about this, so I updated the code to automatically load the checkpoint.
