### ISSUE TITLE
linux extract mobilenet_v2.pth.tar and it is empty?

### ISSUE THREAD

**Issue by pianogGG** [tonylins/pytorch-mobilenet-v2#36]
tar -xvf mobilenet_v2.pth.tar
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
ll mobilenet_v2.pth.tar
-rwxrwxrwx 1 *** users 14205652 Jul  7 20:52 mobilenet_v2.pth.tar*

**Comment by Bangbanggetnithecar** [comment]
me too

**Comment by Kitsunetic** [comment]
me too

```bash
$ tar -xvf mobilenet_v2.pth.tar 

tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

**Comment by tonylins** [comment]
Hi, sorry for the naming confusion. You should not try to untar it. Instead, directly load it in PyTorch: https://github.com/tonylins/pytorch-mobilenet-v2/blob/master/MobileNetV2.py#L140.
