### ISSUE TITLE
file broken ?

### ISSUE THREAD

**Issue by ouceduxzk** [tonylins/pytorch-mobilenet-v2#7]
Hi, I downloaded the file and try to unzip or untar it, but did not succeed, I tried both on ubuntu and mac, no good luck. Can you make sure the file is still good ? 

Thanks in advance

**Comment by tonylins** [comment]
Hi,

You don't have to unzip it. Just follow the **Usage** section and I guess everything will be OK.

**Comment by ouceduxzk** [comment]
thanks, my bad
