### ISSUE TITLE
How do you  preprocess your data?

### ISSUE THREAD

**Issue by guicunbin** [tonylins/pytorch-mobilenet-v2#8]
my preprocess is:    

(1)   firstly,        resize to 256x256;
(2)   secondly,   Subtract the imagenet mean,    then    divided by 256;
(3)    finally,       center crop to 224x224;

then feed  these validation data to your   mobilenet_v2,    but  I didn't  reach your accuracy.

**Comment by itijyou** [comment]
@guicunbin So do you mind to share the accuracy you actually got? Thanks!
